### ISSUE TITLE
Add Algorithms in any language

### ISSUE THREAD

**Issue by memr5** [memr5/Algorithms#4]
This issue is for HACKTOBERFEST'19

**Comment by Vishal260700** [comment]
@memr5 Added basic Mathematical Algorithms (GCD and LCM of Array elements) in python. Check #8

**Comment by tiagopedutti** [comment]
#9 Added Heap Sort Algorithm in C++

**Comment by anwaysomani** [comment]
@memr5 ... #14 Bucket sort algorithm in Python added

**Comment by prkhrv** [comment]
Added Linear Search in python .

**Comment by Ritesh-Ag** [comment]
Added Bubble Sort in C #34

**Comment by Ritesh-Ag** [comment]
Added Binary Searching in C++ #35

**Comment by Akshayy99** [comment]
@memr5 i added KMP algorithm for string matching in C++.

**Comment by jasmaa** [comment]
Added bubble sort in Python https://github.com/memr5/Algorithms/pull/43

**Comment by jasmaa** [comment]
Added coin change in Python https://github.com/memr5/Algorithms/pull/44

**Comment by ABHI165** [comment]
I will Add Quick Sort in C

**Comment by Criptdestroyer** [comment]
I will add permutation of integer in java

**Comment by ABHI165** [comment]
I will add Heap Sort in C Language

**Comment by Kuljeet-123** [comment]
@memr5 please review my PR and merge into your repo and my PR id is #99

**Comment by smdp2000** [comment]
@memr5 Added 2D array spiral order traversal #141 , review my pr

**Comment by anil-goudar** [comment]
I will add Rabin Karp string matching using python

**Comment by aditya2499** [comment]
I will add the Longest Common Subsequence in C++

**Comment by Vanish-ka** [comment]
@memr5 Added code for two sum problem #190

**Comment by eric3119** [comment]
add ford fulkerson https://github.com/memr5/Algorithms/pull/191

**Comment by akshayjain3450** [comment]
Hey @memr5 Added Astar Algorithm with implementation in Python. Review my pr #193

**Comment by rak108** [comment]
hello, 
ive added algorithm in dynamic program to find nth catalan number.
kindly check given PR
https://github.com/memr5/Algorithms/pull/195

**Comment by usman18** [comment]
I have added Bubble Sort in Dart language in folder Dart.
Check #199

**Comment by hackbansu** [comment]
Add code for Tim Sort in JAVA #224

**Comment by BakedScorpion** [comment]
@memr5  Added Radix sort code:- #234
