### ISSUE TITLE
Add Searching Algorithms in any Language

### ISSUE THREAD

**Issue by memr5** [memr5/Algorithms#51]
Only add Algorithms which are not already present in the repository.

**Comment by i-m-vivek** [comment]
I want to add binary search in python.

**Comment by ABHI165** [comment]
I will add linear search in C

**Comment by ABHI165** [comment]
i want to add Binary search in C

**Comment by i-m-vivek** [comment]
Added Jump search in python #63

**Comment by ShubhamRattra** [comment]
i would like to binary search in c

**Comment by Criptdestroyer** [comment]
Added Jump Search in Java

**Comment by aansari4599** [comment]
i would like to add Jump Search in c++

**Comment by purplesmurf45** [comment]
i would like to add insertion sort in c

**Comment by Deepansharora27** [comment]
I Would Like to add Linear Search in C++

**Comment by sudoalgorithm** [comment]
Would love to add search algorithm in Golang let me know if that is still a option

**Comment by dhanoz** [comment]
Iwould love to add bubble sort

**Comment by dhanoz** [comment]
I would love to add bubble sort
